# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: Dagger Panorama
# label used for menu selection
label: dagger_firewall_agent
description: Configures a Panorama User-ID agent 


# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Dagger Skillets

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: agent_name
    description: User-ID agent name
    default: Panorama
    type_hint: text
  
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: firewall_agent
    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='{{ template_name }}']/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='{{ template_vsys }}']/user-id-agent
    file: agent.xml
# ---------------------------------------------------------------------
# end of snippets section